global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']  # RabbitMQ management port
    scrape_interval: 30s

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9000']  # QuestDB web console port
    scrape_interval: 30s