version: "3.9"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testadmin
      MONGO_INITDB_ROOT_PASSWORD: testadmin
      MONGO_INITDB_DATABASE: "peopledb"
    volumes:
      - ./setup/mongo-init-scripts:/docker-entrypoint-initdb.d

  server:
    container_name: telemetry-ingest
    image: golang:1.23
    # restart: unless-stopped
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run subscriber.go
    depends_on:
      - mongodb
    links:
      - "mongodb:db"
