apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: PBFA97CFB590B2093
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      httpMethod: POST

  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb:8812
    database: qdb
    user: admin
    uid: questdb
    secureJsonData:
      password: quest
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: true
    jsonData:
      maxLines: 1000