global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  - job_name: 'rabbitmq-metrics'
    static_configs:
      - targets: ['rabbitmq:15692']  # RabbitMQ Prometheus metrics port
    scrape_interval: 15s

  - job_name: 'questdb-metrics'
    static_configs:
      - targets: ['questdb:9003']  # QuestDB metrics port
    scrape_interval: 15s

