version: "3.8"

services:
  go_app:
    build: .
    container_name: go-telemetry
    restart: "on-failure"
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - telemetry-network
    environment:
      KAFKA_URL: "localhost:9092,localhost:9095"
      MAX_BATCH_SIZE: "5000"
      BATCH_TIMEOUT: "1s"
      MAX_RETRIES: "3"
      RETRY_DELAY: "500ms"
      PARALLEL_GROUPS: "1"
      BATCH_SIZE: "3000"
      GOMAXPROCS: "0"
      GOGC: "100"
    volumes:
      - ./ibt_files:/app/ibt_files
    entrypoint:
      [
        "/app/telemetry-app",
        "/app/ibt_files/mclaren720sgt3_monza full 2025-02-09 12-58-11.ibt",
      ]

networks:
  telemetry-network:
    external: true
