version: "3.8"

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
    secrets:
      - influxdb-admin-username
      - influxdb-admin-password
      - influxdb-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

  go_app:
    build: .
    container_name: go-telemetry
    restart: always
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: myorg
      INFLUXDB_BUCKET: telemetry
      INFLUXDB_TOKEN_FILE: /run/secrets/influxdb-admin-token
    secrets:
      - influxdb-admin-token
    volumes:
      - ./ibt_files:/app/ibt_files
    entrypoint:
      [
        "/app/telemetry-app",
        "/app/ibt_files/mclaren720sgt3_monza full 2025-02-09 12-58-11.ibt",
      ]

secrets:
  influxdb-admin-username:
    file: ./.env.influxdb-admin-username
  influxdb-admin-password:
    file: ./.env.influxdb-admin-password
  influxdb-admin-token:
    file: ./.env.influxdb-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
