version: "3.8"

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
    secrets:
      - influxdb-admin-username
      - influxdb-admin-password
      - influxdb-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - telemetry-network
    deploy:
      resources:
        limits:
          cpus: ".3"
          memory: 1G

  go_app:
    build: .
    container_name: go-telemetry
    restart: "no"
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - telemetry-network
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: myorg
      INFLUXDB_BUCKET: telemetry
      INFLUXDB_TOKEN_FILE: /run/secrets/influxdb-admin-token
      # Performance tuning
      MAX_BATCH_SIZE: "5000"
      BATCH_TIMEOUT: "1s"
      MAX_RETRIES: "3"
      RETRY_DELAY: "500ms"
      PARALLEL_GROUPS: "4"
      BATCH_SIZE: "1000"
      # Golang performance tuning
      GOMAXPROCS: "0" # Let Go determine based on available CPUs
      GOGC: "100" # Default garbage collection threshold
    secrets:
      - influxdb-admin-token
    volumes:
      - ./ibt_files:/app/ibt_files
    entrypoint:
      [
        "/app/telemetry-app",
        "/app/ibt_files/mclaren720sgt3_monza full 2025-02-09 12-58-11.ibt",
      ]
    deploy:
      resources:
        limits:
          cpus: ".3"
          memory: 1G

secrets:
  influxdb-admin-username:
    file: ./.env.influxdb-admin-username
  influxdb-admin-password:
    file: ./.env.influxdb-admin-password
  influxdb-admin-token:
    file: ./.env.influxdb-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  telemetry-network:
    external: true
    name: telemetry-network
